on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@v2
    - name: setup-python
      uses: actions/setup-python@v2
    - name: Install dependencise
      run: |
        python -m pip install --upgrade pip
        pip install pylint
      

